New CLI flag: `do_not_remove_comments_in_macro`.
standardese/standardese pull request #216
Opened 2021-11-10 09:54 UTC by kuredoro

Fixes #206. This potentially allows practically any project that uses Boost ASIO (and not only) to be correctly parsed by standardese by default.

This PR adds the new flag and exports compile_commands.json by default.

2021-11-14 13:19 UTC, saraedum requested changes
Thanks for your contribution. That's certainly a cppast flag that we would like to expose.

We'll probably shorten the command line flags to their corresponding compiler/preprocessor flags in some future release and expose this as `--CC` additionally but in the meantime having this available as `--compilation.keep_comments_in_macro` sounds good to me.

2021-11-14 13:19 UTC, saraedum commented on tool/main.cpp
> +        ("compilation.do_not_remove_comments_in_macro",
```suggestion
        ("compilation.keep_comments_in_macro",
```

2021-11-14 13:19 UTC, saraedum commented on tool/main.cpp
> +         "enable/disable removal of comments during macro evaluation")
```suggestion
         "enable/disable removal of comments during macro evaluation (-CC)")
```

2021-11-14 15:26 UTC, kuredoro commented on tool/main.cpp
> +        ("compilation.do_not_remove_comments_in_macro",
That's surely a better name!

2021-11-14 15:26 UTC, kuredoro commented on tool/main.cpp
> +         "enable/disable removal of comments during macro evaluation")
Reworded.

2021-11-14 15:36 UTC, saraedum commented
Sorry, I forget. Could you announce your change in `doc/news`?

2021-11-14 15:54 UTC, kuredoro commented
In `news/`...? Should I copy the template and put my change under `Added:`? What should this file be called?

2021-11-14 17:12 UTC, saraedum commented
Sorry, I should have been more explicit. The file can have any name, typically, the name of the branch `remove_comments_in_macro_flag.rst`. And yes, just mention your change under `Added:` or maybe rather under `Fixed:`. The other sections can be deleted from that file. Or kept around, it does not matter.

2021-11-14 17:13 UTC, saraedum commented
The news file is then used by rever, the documentation is here if you are curious: https://regro.github.io/rever-docs/news.html

2021-11-18 09:18 UTC, kuredoro commented
Wrote it :)
Can you check, please?

2021-11-18 18:03 UTC, merged

2021-11-18 18:03 UTC, saraedum commented
Thanks a lot :)